steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/etl-cloud-run:latest', '.']
    env: ['DOCKER_BUILDKIT=1']
    id: Build
    waitFor: ['-']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/etl-cloud-run:latest']
    id: Push
    waitFor: ['Build']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'etl-service',
           '--image', 'gcr.io/$PROJECT_ID/etl-cloud-run:latest',
           '--platform', 'managed',
           '--region', 'us-central1',
           '--allow-unauthenticated']

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/etl-cloud-run:latest'