file_delimiter_mapping:
  hackers.csv: '|'

# Configurações de paralelismo
parallelism:
  max_workers_io: 5      # Para operações I/O-bound (ThreadPoolExecutor)
  max_workers_cpu: 4     # Para operações CPU-bound (ProcessPoolExecutor)